const AuthActionTypes = {
  GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',
  LOGIN_WITH_EMAIL_START: 'LOGIN_WITH_EMAIL_START',
  LOGIN_WITH_EMAIL_SUCCESS: 'LOGIN_WITH_EMAIL_SUCCESS',
  LOGIN_WITH_EMAIL_FAIL: 'LOGIN_WITH_EMAIL_FAIL',
  LOGIN_WITH_OAUTH_START: 'LOGIN_WITH_OAUTH_START',
  LOGIN_WITH_OAUTH_SUCCESS: 'LOGIN_WITH_OAUTH_SUCCESS',
  LOGIN_WITH_OAUTH_FAIL: 'LOGIN_WITH_OAUTH_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  REGISTER_WITH_EMAIL_START: 'REGISTER_WITH_EMAIL_START',
  REGISTER_WITH_EMAIL_SUCCESS: 'REGISTER_WITH_EMAIL_SUCCESS',
  REGISTER_WITH_EMAIL_FAIL: 'REGISTER_WITH_EMAIL_FAIL',
};

export default AuthActionTypes;
